name: Rust

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  PROFILE: release

jobs:
  rust:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    with:
        image-prefix: "samply/"
        components: '[ "prism" ]'
        test-via-script: false
        push-to: ${{ (github.ref_protected == true || github.event_name == 'workflow_dispatch') && 'dockerhub' || 'none' }}
    secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
